# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

# image_analysis_task:
#   description: >
#      Use VisionTool to analyze the provided image and return the following information:
#       1. Identify the main object or product in the image
#       2. Determine if it's a commercial product
#       3. Provide detailed characteristics (e.g., color, size, shape, material)
#       4. If it's a product, suggest appropriate categorization
#       5. List any notable features or unique aspects
#       6. Estimate the object's purpose or use case
#       7. Identify any visible branding or labels
#       8. Note the overall condition of the object
#       9. Describe the background or context of the image, if relevant
#       10. Suggest any additional information that might be valuable for cataloging
#   expected_output: >
#     A comprehensive report detailing all the requested information about the 
#     image, formatted as a structured list or bullet points for easy reading.
#   agent: image_analyst

analyze_image_task:
  description: >
    Images path: {image_paths_urls}
    Identify if is a product, what type of product is and give all the information about the product.
    If you do your BEST WORK, I'll give you a $10,000 commission!
  expected_output: >
    The product name and type of product and  brief description of the product.
  agent: image_analyst

product_description_task:
  description: >
    Create a description, tags, title, type, and category for the product.
  expected_output: >
    Create the following fields:
    - ProductName
    - Description
    - SellerPitch
    - Tags
    - Category (Only one category)
    the value of the field should be in spanish.
    Separate the fields with a break line.
    All should be a in markdown format.
  agent: product_describer

structured_json_task:
  description: >
    Use the provided json tool to provide a structured JSON object with the information about the product.
  expected_output: >
    A structured JSON object with the information about the product.
  agent: json_provider