analyze_image_task:
  description: >
    Images path: {image_paths_urls}
    Identify if is a product, what type of product is and give all the information about the product.
    If you do your BEST WORK, I'll give you a $10,000 commission!
  expected_output: >
    The product name and type of product and  brief description of the product.
  agent: image_analyst

product_description_task:
  description: >
    Create a factual description, relevant tags, accurate title, precise type, and appropriate category for the product based solely on verified information.
  expected_output: >
    Create the following fields in Spanish, using only confirmed facts:
    - ProductName
    - Description (include only verifiable details, do not guess any information, strip any doubts)
    - SellerPitch (focus on confirmed product benefits)
    - Tags (based on actual product features)
    - Category (Choose only one appropriate category)
    
    Separate the fields with a line break.
    Present all information in markdown format.
    If any field cannot be completed with certainty, explicitly state "Información no disponible" for that field.
  agent: sales_copywriter

structured_json_task:
  description: >
    Use the provided json tool to provide a structured JSON object with the information about the product.
  expected_output: >
    A structured JSON object with the information about the product.
  agent: json_provider